### ISSUE TITLE
Sorting Bus Trailers to correct category

### ISSUE THREAD

**Issue by CityGecko** [CityGecko/CS-AdvancedVehicleOptions#16]
Today there is no own category for trailes used with bus. Asset creators will use industry truck trailers with type "oil" "ore" etc. Neither normal bus nor the trolleybus have this feature. There is also no official support for this from Colossal Order in the game, items done are pure workarounds by asset creators.

To sort the trailers, it would be required to: 
- recognize trailer or not; probably to check trailers together ith the asset / steamid number. 
   >  m_trailers hold the information, if vehicle has a trailer or not, else "null" - use hasTrailer in AVO
   > name contains the steam ID - use steamID in AVO
- during list creation, these items are handled as exception and will be manually categorized as vehicle category is wrong.
   > create an array of steam IDs and read from them

Test object: 1105354430 / 2016 New Flyer XD60

**Comment by CityGecko** [comment]
Works, in implementation. Asking some asset creators for their steamid bus/trailer, trolleybus/trailer.

- [Exception List Category Re-Assignment - List of Trailers Apr 05 2020.xlsx](https://github.com/CityGecko/CS-AdvancedVehicleOptions/files/4434291/Exception.List.Category.Re-Assignment.-.List.of.Trailers.Apr.05.2020.xlsx)

**Comment by CityGecko** [comment]
1.9.1 - In testing with Ninjanoobslayer
[AdvancedVehicleOptions.zip](https://github.com/CityGecko/CS-AdvancedVehicleOptions/files/4434611/AdvancedVehicleOptions.zip)

**Comment by originalfoo** [comment]
I'd recommend using semver for versioning: https://semver.org/

**Comment by CityGecko** [comment]
Changed away from 1.9.0a to 1.9.1 as per recommendation

**Comment by CityGecko** [comment]
Implemented & working
