### ISSUE TITLE
Trailer Vehicle Reference List

### ISSUE THREAD

**Issue by CityGecko** [CityGecko/CS-AdvancedVehicleOptions#19]
Asset Creators will use this Issue Log to add new references for industrial trailers, which are used in combination with Bus, Trolley Bus, Police Vehicles, Fire Safety Vehicles.

Ground Rules: supply information as per the attached Excel.

Once information is supplied, the next update of AVO will carry the updated references. These references are maintained in the file AdvancedVehicleOptions / Compatibility / TrailerVehiclesCompatibilityPatch.cs

[Exception List Category Re-Assignment - List of Trailers Apr 05 2020.xlsx](https://github.com/CityGecko/CS-AdvancedVehicleOptions/files/4446683/Exception.List.Category.Re-Assignment.-.List.of.Trailers.Apr.05.2020.xlsx)

**Comment by dolanbaker** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1271872968  Post Lorry should be categorised as "postal service" and not "industry delivery" 
It is a vehicle that is used to move mail between sorting offices and post offices.

**Comment by CityGecko** [comment]
> Post Lorry should be categorised as "postal service" and not "industry delivery"
> It is a vehicle that is used to move mail between sorting offices and post offices.

Hi Dolanbaker - I wrote a message to the original author, if he can re-classify his assets to the correct category. Lets wait for it and if no reply, I will add it to the exception list.

Rgds
Tim
