### ISSUE TITLE
Wrong modal behavior 

### ISSUE THREAD

**Issue by MacSergey** [CityGecko/CS-AdvancedVehicleOptions#26]
You should check `UIView.HasModalInput()` and hide `GetUIView().panelsLibraryModalEffect` only if false. Otherwise you broke another modal windows

https://github.com/CityGecko/CS-AdvancedVehicleOptions/blob/dce4508060b97f6efec21131100dc809ce3094e5/AdvancedVehicleOptions/GUI/UIWarningModal.cs#L119

**Comment by CityGecko** [comment]
else if (modalEffect != null && !UIView.HasModalInput())
-- fix for 1.9.5
