### ISSUE TITLE
Option to set train trailer stats to same as engine vehicle

### ISSUE THREAD

**Issue by originalfoo** [CityGecko/CS-AdvancedVehicleOptions#30]
When setting the accel/brake/turning of large trains, it's tedious to have to do it for each trailer. Would it be possible to get a mod option that, when enabled, will set the trailer stats same as engine stats?

For example, I choose an engine and set it's accel/brake = 0.2... all the trailers of that train would be updated to accel/brake = 0.2

Replicable stats:

* Max speed
* Acceleration
* Brake
* Turning
* Springs
* Dampers
* Lean
* Nod

The stat would only be copied to trailers when edited (sometimes trailers have slightly slower stats, particularly with some of REV0's more advanced trainsets).

The option would be available for cargo/passenger trains, trams, metros primarily. 

Ideally the option could be placed as a checkbox at the top-right of the title bar? That way I can easily toggle the option on/off while editing vehicles, without needing to constantly go back and fourth to the mod settings screen.

**Comment by CityGecko** [comment]
Hallo aubergine10, that sounds useful. If you have potentially some time, feel free to commit lines for code. The UI is a bit cumbersome, but I think it should be manageable.

**Comment by CityGecko** [comment]
Delivered in 1.9.8
