### ISSUE TITLE
Industries DLC - Animal products not being collected

### ISSUE THREAD

**Issue by Produktecheck** [CityGecko/CS-AdvancedVehicleOptions#34]
AVO Version 1.9.8

The trucks don't spawn to sell the animal products. If I disable the mod it works.

**Comment by CityGecko** [comment]
Hi Produktecheck

Did you accidentally deactivate the Livestock Truck ? All animals are transported with a Livestock Truck only. If you deactivate the vanilla one, no truck will spawn. You need the vanilla one or any workshop replacement.

I have three trucks available: 2x Peterbilt from Workshop, and the vanilla one. 
![grafik](https://user-images.githubusercontent.com/44513201/181346819-faaf586e-f766-451d-a72e-fa655bb86f20.png)

The vanilla one is deactivated. but the Peterbilts are active.
![grafik](https://user-images.githubusercontent.com/44513201/181347654-841657ef-dab1-4799-89c4-d9943b24e58e.png)

**Comment by Produktecheck** [comment]
Many thanks for the answer. It's finally working again ;)
