### ISSUE TITLE
Error in linux

### ISSUE THREAD

**Issue by sperez-salgado** [CityGecko/CS-AdvancedVehicleOptions#40]
Hi, 

when starting the game, an error occurs in AdvancedVehicleOptions.dll. BankVanAI from Assembly.CSharp cannot be loaded.

Regards.

![Screenshot_2023-02-15_19-58-16](https://user-images.githubusercontent.com/71145076/219248069-24d2d135-a326-4aa1-9225-2c6d96b2cf1b.png)

**Comment by CityGecko** [comment]
Hi Sperez - I do not own the Linux version (nor running Linux, but I try to find out, what is the issue here. Maybe a dependency for the DLC, but it should not.

**Comment by sperez-salgado** [comment]
Hi, again.

After updating the game to the latest version (using Steam) the problem was solved.

Thanks.
