### ISSUE TITLE
Toolbar Button will not show in Scenarios

### ISSUE THREAD

**Issue by CityGecko** [CityGecko/CS-AdvancedVehicleOptions#5]
User Notification on Steam: Toolbar Button for AVO will not show up when starting scenario / verified, confirmed issue

**Comment by originalfoo** [comment]
Should be easy to fix - probably just missing a load mode in this method:

https://github.com/CityGecko/CS-AdvancedVehicleOptions/blob/master/AdvancedVehicleOptions/AdvancedVehicleOptions.cs#L90

Is it OK if I split out the `LoadingExtension` from that main `AdvancedVehicleOptions.cs`?

**Comment by CityGecko** [comment]
Ok, understand, so there is also a value for "Scenarios" in that case.  Is the value "NewMap" ? If yes, the line 95 should show something like...

 _if (mode != LoadMode.LoadGame && mode != LoadMode.NewGame && mode !=LoadMode.NewMap )_

Or should this re-written like this ? https://github.com/citiesskylines-csur/CSURToolBox/blob/master/Loader.cs#L61

**Comment by CityGecko** [comment]
Fixed.

**Comment by originalfoo** [comment]
Hey, sorry for late reply - been crazy busy. In TM:PE we're planning to use something like this:

```cs
        public bool IsApplicable(LoadMode mode) {
            return mode == LoadMode.LoadGame
                || mode == LoadMode.LoadScenario
                || mode == LoadMode.NewGame
                || mode == LoadMode.NewGameFromScenario;
        }
```

So that way we know explicitly which modes are going to be accepted and it won't break if CO add any new types of `LoadMode`.

Then we do this:

```cs
public void OnLevelLoaded(LoadMode mode) {
    if (!IsApplicableMode(mode)) {
        return; // not interested in this mode
    }

    // code to run after user starts or loads a city or scenario
}
```

**Comment by originalfoo** [comment]
the `LoadMode.NewMap` is map editor mode I think

**Comment by CityGecko** [comment]
Thanks Aubergine for feedback. I was able to manage this little issue today after finally finding something, that helps a bit to understand the API (https://skylines.paradoxwikis.com/Modding_API).

Now I check for 3 modes in the beginning, Loading Savegame, Starting New Game from a Map and Starting a Scenario. Works for me and now shows AVO also in fresh started scenarions.

**Comment by CityGecko** [comment]
btw -- Github has now the 1.9.0 release for AVO. If you come from 1.8.5 it always raises an exception. It will be only once, when users go from 1.8.5 to 1.9.0 - I do not know, where to capture the exception, that it is ignored and user will not see it. I think it comes from AVO try to loading variables from the serializer (the new ones, which were added and those are not in the savegame file). If any idea how to suppress, let me know :).

**Comment by originalfoo** [comment]
if i get chance i'll test later today and see if I can work out what's causing it or how to hide the error
